AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: |
  Centralized Lambda and SNS alerting system for CloudTrail activity across AWS Organization. Deployed in the Audit account.

Parameters:
  OrgId:
    Type: String
    Description: AWS Organization ID (e.g., o-xxxxxxxxxx)
  SNSTopicName:
    Type: String
    Default: CloudTrailSecurityAlerts
  AccountIds:
    Type: CommaDelimitedList
    Description: List of account IDs to monitor
  LambdaS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment packages
  AlertHandlerKey:
    Type: String
    Description: S3 key for the Alert Handler Lambda .zip file
    Default: LambdaFunctions/CentralCloudTrailAlertHandler.zip

Resources:
  'Fn::ForEach::Accounts':
    - AccountId
    - !Ref AccountIds
    - CrossAccountExecFrom${AccountId}:
        Type: AWS::Lambda::Permission
        Properties:
          Action: lambda:InvokeFunction
          FunctionName: !Ref CloudTrailAlertLambda
          Principal: !Sub arn:aws:iam::${AccountId}:root
          SourceAccount: !Sub ${AccountId}

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'CentralCloudTrailAlertLambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLoggingAndSNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SNSTopicName

  CloudTrailAlertLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CentralCloudTrailAlertHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Runtime: python3.13
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref AlertHandlerKey
      Environment:
        Variables:
          ACCOUNT_IDS: !Join
            - ','
            - !Ref AccountIds
          SNS_TOPIC_ARN: !Ref SNSTopic
      Timeout: 30

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function to use in EventBridge rules in member accounts
    Value: !GetAtt CloudTrailAlertLambda.Arn

  SNSTopicArn:
    Description: ARN of the SNS Topic used for alerts
    Value: !Ref SNSTopic
